fullnameOverride: flight-service

image:
  repository: ""
  tag: "latest"

service:
  port: 8060

env:
  - name: DOCKER_CONNECT_STRING
    value: "Host=postgres;Port=5432;Database=flights;Username=postgres;Password=postgres"
