appName: "bonus-service"
replicaCount: 2
image:
  repository: "solom/bonus-service"
  tag: "v1"
service:
  port: 80
  targetPort: 80
ingress:
  enabled: true
  host: "api.example.com"
  path: "/api/v1/privilege"
database:
  name: "privilege_db"
  secretName: "postgres-secret"